### ISSUE TITLE
Error occurred when executing BatchCreativeInterpolation

### ISSUE THREAD

**Issue by yyniao** [banodoco/Steerable-Motion#14]
Hi there,

I'm getting an error when trying to use BatchCreativeInterpolation in your project. The error message is 

"Error occurred when executing BatchCreativeInterpolation:
'ControlNet' object has no attribute 'load_device'

![image](https://github.com/banodoco/Steerable-Motion/assets/35762396/9f23dc93-750b-401e-ae83-7295ebbf3a48)

**Comment by peteromallet** [comment]
Hi @yyniao, could you try updating that to the latest version of Comfy? I think it could be due to some changes that were made to the CN stuff to accommodate the latest version of Comfy that aren't backwards compatible

**Comment by yyniao** [comment]
> Hi @yyniao, could you try updating that to the latest version of Comfy? I think it could be due to some changes that were made to the CN stuff to accommodate the latest version of Comfy that aren't backwards compatible

Hi, I downloaded the latest version of ComfyUI, but I'm still encountering the same error message.

**Comment by peteromallet** [comment]
Could you try uninstalling and reinstalling? There was a breaking change that touches the impacted code and it feels likely it's related to that

**Comment by yyniao** [comment]
> Could you try uninstalling and reinstalling? There was a breaking change that touches the impacted code and it feels likely it's related to that

Thank you for your patience. I ran update_comfyui.bat. It worked.
