### ISSUE TITLE
Error occurred when executing BatchCreativeInterpolation

### ISSUE THREAD

**Issue by RuneGjerde** [banodoco/Steerable-Motion#18]
Error occurred when executing BatchCreativeInterpolation:

Error(s) in loading state_dict for ImageProjModelImport:
size mismatch for proj.weight: copying a param with shape torch.Size([3072, 1024]) from checkpoint, the shape in current model is torch.Size([3072, 1280]).

---

Everything up to date. ComfyUI as well as extensions

**Comment by RuneGjerde** [comment]
changing IP Adapter to "ip-adapter_sd15_vit5.safesensor" makes the workflow work without any errors. 

Using the standard "ip-adapter_sd15.safesensor" will reproduce the error above. 

Not sure if this is any relevant or not, or a random fluke of luck ;-)

**Comment by peteromallet** [comment]
Weird, ip-adapter_sd15.safesensor worked for me. Thanks for the report 🖖

**Comment by cheezecrisp** [comment]
Same Error when using ip-adapter_sd15 and ip-adapter_sd15_light.

**Comment by guahunyo** [comment]
Same Error when using ip-adapter_sd15 and ip-adapter-plus_sd15.
