### ISSUE TITLE
AttributeError: 'ControlNet' object has no attribute 'load_device'

### ISSUE THREAD

**Issue by 0xech0** [banodoco/Steerable-Motion#19]
'ControlNet' object has no attribute 'load_device'. Fresh install of steerable motion

Full error: 

> 'ControlNet' object has no attribute 'load_device'
> 
> File "/opt/rd/ComfyUI/execution.py", line 153, in recursive_execute
> output_data, output_ui = get_output_data(obj, input_data_all)
> File "/opt/rd/ComfyUI/execution.py", line 83, in get_output_data
> return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
> File "/opt/rd/ComfyUI/execution.py", line 76, in map_node_over_list
> results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
> File "/opt/rd/ComfyUI/custom_nodes/steerable-motion/SteerableMotion.py", line 323, in combined_function
> control_net = control_net_loader.load_controlnet(control_net_name, timestep_keyframe)[0]
> File "/opt/rd/ComfyUI/custom_nodes/steerable-motion/imports/AdvancedControlNet/nodes.py", line 86, in load_controlnet
> controlnet = load_controlnet(controlnet_path, timestep_keyframe)
> File "/opt/rd/ComfyUI/custom_nodes/steerable-motion/imports/AdvancedControlNet/control.py", line 728, in load_controlnet
> return convert_to_advanced(control, timestep_keyframe=timestep_keyframe)
> File "/opt/rd/ComfyUI/custom_nodes/steerable-motion/imports/AdvancedControlNet/control.py", line 737, in convert_to_advanced
> return ControlNetAdvancedImport.from_vanilla(v=control, timestep_keyframe=timestep_keyframe)
> File "/opt/rd/ComfyUI/custom_nodes/steerable-motion/imports/AdvancedControlNet/control.py", line 630, in from_vanilla
> global_average_pooling=v.global_average_pooling, device=v.device, load_device=v.load_device, manual_cast_dtype=v.manual_cast_dtype)`
> 
>

**Comment by pdbarma** [comment]
Same Issue

> 'ControlNet' object has no attribute 'load_device'. Fresh install of steerable motion
> 
> Full error:
> 
> > 'ControlNet' object has no attribute 'load_device'
> > File "/opt/rd/ComfyUI/execution.py", line 153, in recursive_execute
> > output_data, output_ui = get_output_data(obj, input_data_all)
> > File "/opt/rd/ComfyUI/execution.py", line 83, in get_output_data
> > return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
> > File "/opt/rd/ComfyUI/execution.py", line 76, in map_node_over_list
> > results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
> > File "/opt/rd/ComfyUI/custom_nodes/steerable-motion/SteerableMotion.py", line 323, in combined_function
> > control_net = control_net_loader.load_controlnet(control_net_name, timestep_keyframe)[0]
> > File "/opt/rd/ComfyUI/custom_nodes/steerable-motion/imports/AdvancedControlNet/nodes.py", line 86, in load_controlnet
> > controlnet = load_controlnet(controlnet_path, timestep_keyframe)
> > File "/opt/rd/ComfyUI/custom_nodes/steerable-motion/imports/AdvancedControlNet/control.py", line 728, in load_controlnet
> > return convert_to_advanced(control, timestep_keyframe=timestep_keyframe)
> > File "/opt/rd/ComfyUI/custom_nodes/steerable-motion/imports/AdvancedControlNet/control.py", line 737, in convert_to_advanced
> > return ControlNetAdvancedImport.from_vanilla(v=control, timestep_keyframe=timestep_keyframe)
> > File "/opt/rd/ComfyUI/custom_nodes/steerable-motion/imports/AdvancedControlNet/control.py", line 630, in from_vanilla
> > global_average_pooling=v.global_average_pooling, device=v.device, load_device=v.load_device, manual_cast_dtype=v.manual_cast_dtype)`

**Comment by peteromallet** [comment]
Others have fixed this by pressing Update All - and updating to the latest versino of Comfy. Think that this is due to a change  in Comfy that happened last week

**Comment by 0xech0** [comment]
Ye

> Others have fixed this by pressing Update All - and updating to the latest versino of Comfy. Think that this is due to a change in Comfy that happened last week

Tried that and it didn't work for me

**Comment by peteromallet** [comment]
Are you 100% sure you have the latest version of Comfy? This has been revolved in other cases with that + latest nodes - maybe try a reinstall if need be

**Comment by agustincaniglia** [comment]
I am getting this:
Error occurred when executing BatchCreativeInterpolation:

Error(s) in loading state_dict for ResamplerImport:
size mismatch for proj_in.weight: copying a param with shape torch.Size([768, 1280]) from checkpoint, the shape in current model is torch.Size([768, 1664]).

File "H:\AUTOMATIC\COMFYUI\ComfyUI_windows_portable_nvidia_cu118_or_cpu (1)\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "H:\AUTOMATIC\COMFYUI\ComfyUI_windows_portable_nvidia_cu118_or_cpu (1)\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "H:\AUTOMATIC\COMFYUI\ComfyUI_windows_portable_nvidia_cu118_or_cpu (1)\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "H:\AUTOMATIC\COMFYUI\ComfyUI_windows_portable_nvidia_cu118_or_cpu (1)\ComfyUI_windows_portable\ComfyUI\custom_nodes\steerable-motion\SteerableMotion.py", line 347, in combined_function
model, = ipadapter_application.apply_ipadapter(ipadapter=ipadapter, model=model, weight=1.0, image=None, weight_type="original",
File "H:\AUTOMATIC\COMFYUI\ComfyUI_windows_portable_nvidia_cu118_or_cpu (1)\ComfyUI_windows_portable\ComfyUI\custom_nodes\steerable-motion\imports\IPAdapterPlus.py", line 501, in apply_ipadapter
self.ipadapter = IPAdapterImport(
File "H:\AUTOMATIC\COMFYUI\ComfyUI_windows_portable_nvidia_cu118_or_cpu (1)\ComfyUI_windows_portable\ComfyUI\custom_nodes\steerable-motion\imports\IPAdapterPlus.py", line 241, in __init__
self.image_proj_model.load_state_dict(ipadapter_model["image_proj"])
File "H:\AUTOMATIC\COMFYUI\ComfyUI_windows_portable_nvidia_cu118_or_cpu (1)\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 2041, in load_state_dict
raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(

I have updated all custom nodes and comfyUI

**Comment by peteromallet** [comment]
Hi @agustincaniglia, that looks like you're either using a non-SD1.5-based model or differently sized images - this is usually what the tensors not matching means

**Comment by agustincaniglia** [comment]
> Hi @agustincaniglia, that looks like you're either using a non-SD1.5-based model or differently sized images - this is usually what the tensors not matching means

I am using 512x512 images and 1.5 models and get the same error.

**Comment by peteromallet** [comment]
Are you sure you're not using a XL VAE or IPA or something? Definitely something mismatching

> > Hi @agustincaniglia, that looks like you're either using a non-SD1.5-based model or differently sized images - this is usually what the tensors not matching means
> 
> I am using 512x512 images and 1.5 models and get the same error.

**Comment by agustincaniglia** [comment]
okay I think i had a wrong clip model version. its working now apparently.

**Comment by shaaraa** [comment]
I updated comfyUI and it works.

**Comment by microvswind** [comment]
> > Hi @agustincaniglia, that looks like you're either using a non-SD1.5-based model or differently sized images - this is usually what the tensors not matching means
> 
> I am using 512x512 images and 1.5 models and updated comfyui and get the same issue,
![image](https://github.com/banodoco/Steerable-Motion/assets/103630540/e97b42fc-7c57-41b6-ba98-6327935fe523)
![image](https://github.com/banodoco/Steerable-Motion/assets/103630540/ac8319a5-1c61-442b-b867-ccba565a7080)

**Comment by peteromallet** [comment]
Hi @microvswind, is your VAE and other models definitely 1.5?

**Comment by peteromallet** [comment]
Ah see you don't have one - could you try uninstalling and reinstalling it?
