### ISSUE TITLE
Ask a question

### ISSUE THREAD

**Issue by gxbsyxh** [banodoco/Steerable-Motion#22]
Hello great author, I only take 1 minute to animate when using a single image conversion, but half an hour when using 2 images and more than 1 hour for 3 images, is this normal, using the default workflow

**Comment by peteromallet** [comment]
That's definitely not normal - are you using a low RAM GPU, maybe 10gb? I think what may be happening is that when you go to a larger frame count it triggers low ram mode (you should see this in the terminal if it's happening)
