### ISSUE TITLE
How about add Kohya XL Blur controlnet for SteerAble-Motion

### ISSUE THREAD

**Issue by xueqing0622** [banodoco/Steerable-Motion#23]
How about add Kohya XL Blur controlnet for SteerAble-Motion
Kohya XL Blur controlnet just like the tile controlnet in 1.5
https://githubfast.com/kohya-ss/ControlNet-LLLite-ComfyUI
![image](https://github.com/banodoco/Steerable-Motion/assets/114840118/482a207b-22a4-4b31-aae9-2a4105ba5554)

**Comment by peteromallet** [comment]
Thanks, will try it out! The blocker for SDXL rn is that the current version AD XL has some issues and Hotshot XL only does 8 frames
