### ISSUE TITLE
Creative Batch Interpolation node results are not cached

### ISSUE THREAD

**Issue by blepping** [banodoco/Steerable-Motion#30]
i am not sure if this is intended behavior or something wrong on my end, but the node always runs no matter what — it does not matter if absolutely no parameters were changed. if it is expected, it would be a huge usability improvement to change that behavior as it is extremely frustrating to generate for 10-20 minutes and then hit some error combining the frames (after all the sampling is done) and then have to run the entire process from the beginning again. 

or even just minor stuff like wanting to tweak the gamma for the generated set of frames, the only way to do it is outside of comfy when for most other nodes it would be possible to just stick an image manipulation node in near the end of the process and only the stuff downstream from that would run

**Comment by peteromallet** [comment]
Hi @blepping, could you share an example of a workflow that does what you're describing well? Usually issues combining the frames are rare - some people had interpolator issues but they're usually resolved

**Comment by blepping** [comment]
thanks for the reply! just to be clear, are you saying that it is _not_ expected behavior for the node to run again when parameters weren't changed? one example of a workflow is the provided example, but i've seen this behavior on every use of the CBI node — it always runs no matter what and of course that means everything downstream runs too. if this isn't expected behavior, then it is probably something on my end. i have a lot of comfy custom nodes installed, and probably some that do stuff like patch the workflow executor. i haven't had this issue with any other nodes though.

>  some people had interpolator issues but they're usually resolved

it is possible to fix stuff that breaks, but having to run the whole workflow again is very frustrating. also it can be other stuff, like i decided i want to save the video at a different fps or change the number of loops. with the way it works for me, this means running the entire workflow again which could take 10-20min

**Comment by peteromallet** [comment]
Just to be clear, you're saying that the node runs again automatically after it's been executed? That's definitely not expected  if so

**Comment by blepping** [comment]
> Just to be clear, you're saying that the node runs again automatically after it's been executed?

ah, no. i mean if you run the workflow, let it complete, and then requeue it again the normal comfy behavior (assuming stuff like fixed seeds) is that nothing happens because none of the parameters changed. so nodes only run when their parameters change normally which means you can add in nodes downstream or change parameters downstream without having the upstream nodes run again - the results from them are cached. however the CBI node just always runs every time the workflow runs, even when no parameters have changed.

**Comment by peteromallet** [comment]
Hi @blepping,

So sorry for the delay in following up here. You're correct that what you describe is conventional in Comfy - however, I changed it for our node because people frequently run the same video workflows again and again without changing the settings.

To work as you expect, go to custom_nodes/Steerable-Motion/SteerableMotion.py and delete the following code:

```
    @classmethod
    def IS_CHANGED(cls, **kwargs):
        return float("NaN")
```

**Comment by blepping** [comment]
@peteromallet thanks for the reply!

>  I changed it for our node because people frequently run the same video workflows again and again without changing the settings.

i have to say i seriously don't understand this. if people run the same workflow again and again and 1) none of the inputs changed, 2) none of the parameters changed then if you force everything to be recomputed you will get exactly the same result, except the user will have to wait 10 minutes for the workflow to complete.

the idea of comfyui is predicated on nodes running when there is actually work to do so this is very confusing from a user perspective. for a lot of nodes it actually wouldn't be a huge deal, but video/animation in particular is so time and compute intensive that forcing the workflow to run again even when it's unnecessary makes a really big difference for the user.

is there anything specific you are trying to work around or accomplish by forcing the workflow to _always_ run? maybe there is a better way to deal with the issue
