### ISSUE TITLE
not an issue - question on refactoring node to use upstream ipadapter loader

### ISSUE THREAD

**Issue by johndpope** [banodoco/Steerable-Motion#31]
basically i have 2 repos - 
https://github.com/cubiq/ComfyUI_IPAdapter_plus

https://github.com/ZHO-ZHO-ZHO/ComfyUI-InstantID

they have different/conflicting implementations of ipadapter loader.

you seem to have harmoniously integrated the 2. 
https://chat.openai.com/share/ffc06449-798a-4ff5-85e1-94e0810b8bab

https://github.com/ZHO-ZHO-ZHO/ComfyUI-InstantID/issues/49

Chatgpt normally gives me good answers - but maybe the question is not accurate.
do I need to throw the Ipadapter_instantidLoader_Node_Zho in the bin? 
but then how to wire up stuff? 

I'll keep digging. 

background - I do have ipadapter_plus working / and the ComfyUI-InstantID was working before.

**Comment by peteromallet** [comment]
Yes, I've heard of Ipadapter_instantidLoader_Node_Zho being problematic - would wait for @cubiq to implement that properly

**Comment by johndpope** [comment]
I solved it 
https://github.com/ZHO-ZHO-ZHO/ComfyUI-InstantID/pull/58
