### ISSUE TITLE
New issue:BatchCreativeInterpolationNode.combined_function() got an unexpected keyword argument 'cn_start_at'

### ISSUE THREAD

**Issue by wujm424606** [banodoco/Steerable-Motion#32]
![image](https://github.com/banodoco/Steerable-Motion/assets/38379474/f60cdf75-1b3c-4cd2-a957-e50bad43a77d)

**Comment by blepping** [comment]
you can use this pull: https://github.com/banodoco/Steerable-Motion/pull/29

**Comment by peteromallet** [comment]
Yes, fixed! Apologies for this
