### ISSUE TITLE
frame get dark and red , need to fix color

### ISSUE THREAD

**Issue by whmc76** [banodoco/Steerable-Motion#34]
![image](https://github.com/banodoco/Steerable-Motion/assets/129386342/e8ec6e10-976a-4cdd-92aa-b5607ef4a06f)
![image](https://github.com/banodoco/Steerable-Motion/assets/129386342/4fcc9d56-34e2-40da-9eba-4a4978ad4908)
here is my settings and output

**Comment by peteromallet** [comment]
There's way too much overlap - try out the default settings from the repo
