### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'encode_image'

### ISSUE THREAD

**Issue by CalebRoenigk** [banodoco/Steerable-Motion#36]
Trying my second attempt at getting Steerable Motion running on my machine but havent had a ton of success. Currently I am running into the error codes:

> ERROR:root:!!! Exception during processing !!!
> ERROR:root:Traceback (most recent call last):
>   File "/Users/calebroegnik/Documents/Comfy UI/ComfyUI/execution.py", line 152, in recursive_execute
>     output_data, output_ui = get_output_data(obj, input_data_all)
>   File "/Users/calebroegnik/Documents/Comfy UI/ComfyUI/execution.py", line 82, in get_output_data
>     return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
>   File "/Users/calebroegnik/Documents/Comfy UI/ComfyUI/execution.py", line 75, in map_node_over_list
>     results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
>   File "/Users/calebroegnik/Documents/Comfy UI/ComfyUI/custom_nodes/steerable-motion/SteerableMotion.py", line 429, in combined_function
>     embed, = ipadapter_encoder.preprocess(clip_vision, prepped_image, True, 0.0, 1.0)
>   File "/Users/calebroegnik/Documents/Comfy UI/ComfyUI/custom_nodes/steerable-motion/imports/IPAdapterPlus.py", line 710, in preprocess
>     clip_embed = clip_vision.encode_image(image)
> AttributeError: 'NoneType' object has no attribute 'encode_image'

So far I have tried:
- Reinstalling ComfyUI and all required nodes
- Double Triple Checking that all the models are downloaded and properly selected

Still have not found a way around this error and can't seem to make heads or tails of the message itself. Any help greatly appreciated!

**Comment by peteromallet** [comment]
This means you're using the wrong Clip Vision model - search up exactly what's in the list of models on the left and use that.
