### ISSUE TITLE
Crashes on Prompt

### ISSUE THREAD

**Issue by CalebRoenigk** [banodoco/Steerable-Motion#37]
Hello!

Back again! I believe I have correctly hooked up all the right models, prompt queues without issue until it reaches the Batch Creative Interpolation node. 
I have gotten this error from the terminal:

> Python[70678:13816514] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!'

I have confirmed I am on the latest version of Python. Not sure what exactly is happening here. If it helps, I am running this on a M1 Mac, which I have a feeling is what is causing the issue.

**Comment by peteromallet** [comment]
Hi @CalebRoenigk, yes, this wasn't available on Mac but it should be at of a latest update. Could you try again?
