### ISSUE TITLE
VAEEncode' has no attribute 'vae_encode_crop_pixels'

### ISSUE THREAD

**Issue by KumaPlayWithShader** [banodoco/Steerable-Motion#41]
Error occurred when executing ACN_SparseCtrlRGBPreprocessor:
type object 'VAEEncode' has no attribute 'vae_encode_crop_pixels'

I  update ComfyUI/Impack Pack/Steerable-Motion, nothing  work.

**Comment by peteromallet** [comment]
You need to update [ComfyUI-Advanced-ControlNet](https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet).
