### ISSUE TITLE
a bug need fix,please help

### ISSUE THREAD

**Issue by T8mars** [banodoco/Steerable-Motion#46]
I like this project,thanks for your node.but when I try to run it, the efficient k-sampler show error,and I try to anthor K-sample it show error two. And I am in a Ai group,when I ask others that I find they have same error two,please check and fix it,We need your help
![b1](https://github.com/banodoco/Steerable-Motion/assets/96167788/a54de7fe-9678-462c-ac71-358ee8cddbdb)
![b2](https://github.com/banodoco/Steerable-Motion/assets/96167788/145a9381-3c4c-406b-b127-e5d186bf7ae8)
![b3](https://github.com/banodoco/Steerable-Motion/assets/96167788/786604f1-bb90-4ea2-85e7-eb066b2f8354)

**Comment by peteromallet** [comment]
I'm going to look into this tomorrow, thanks for flagging

**Comment by T8mars** [comment]
thank you for you relpy
[input_1.zip](https://github.com/banodoco/Steerable-Motion/files/14818952/input_1.zip)
it's the test workflow,I use the 'input1' picture and change the size to 512*512,it run error,but I try to keey same size and parameters ,it run sucessful,so I don't why it happen

**Comment by peteromallet** [comment]
@T8mars, how much RAM do you have? I have a feeling this may be a RAM issue if you have somewhere around 12-16GB and are running on high-detail mode

**Comment by T8star1984** [comment]
@peteromallet I have 16GB of graphics memory and 64GB of memory, and everyone in the group has this problem. Sometimes it's good, but then it reports an error. I need to restart it to work properly, and even changing a parameter can cause this problem. I'm not alone

**Comment by T8star1984** [comment]
I'm in a ai group,someone recommend this node to us.and we all encounter this problem. I send one picture to you,you can see that,

**Comment by T8star1984** [comment]
In group ,a 24GB graphics memory user also encounter this problem too,I think that the ram is not key casuing this error

**Comment by linjian-ufo** [comment]
> 我喜欢这个项目，感谢您的节点，但是当我尝试运行它时，高效的k采样器显示错误，我尝试对K采样它显示错误二。而且我在一个Ai组，当我问其他人我发现他们有相同的错误二时，请检查并修复它，我们需要你的帮助 ![b1](https://private-user-images.githubusercontent.com/96167788/318255645-a54de7fe-9678-462c-ac71-358ee8cddbdb.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMDgxNzUsIm5iZiI6MTcxMjIwNzg3NSwicGF0aCI6Ii85NjE2Nzc4OC8zMTgyNTU2NDUtYTU0ZGU3ZmUtOTY3OC00NjJjLWFjNzEtMzU4ZWU4Y2RkYmRiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDA1MTc1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1OGExNzdkOGZhYWUyMjQ0MWVlYzAzMDRhZjU5M2ZkM2IwZmEyZmRjODM5MzVhMDRkY2NlZTFkNjkwOGM4ZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ue862sRQjDJV1JnrXoWvMwQc0iWBqWHNGLmjk-eDSjY) ![b2](https://private-user-images.githubusercontent.com/96167788/318255656-145a9381-3c4c-406b-b127-e5d186bf7ae8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMDgxNzUsIm5iZiI6MTcxMjIwNzg3NSwicGF0aCI6Ii85NjE2Nzc4OC8zMTgyNTU2NTYtMTQ1YTkzODEtM2M0Yy00MDZiLWIxMjctZTVkMTg2YmY3YWU4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDA1MTc1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1MGRiNDExMDVkZTc5ZGJlOTY4ZjhhNThlYTI0ZWZmNzZjZjY0YTc4MGMzYzdlNWIzYThlNTQ3NWM4NmQ4MzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RL0iZVqzYiNdJcgauSmZO7WWYsXVxCkgliFSsqRyWwc) ![b3](https://private-user-images.githubusercontent.com/96167788/318255662-786604f1-bb90-4ea2-85e7-eb066b2f8354.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMDgxNzUsIm5iZiI6MTcxMjIwNzg3NSwicGF0aCI6Ii85NjE2Nzc4OC8zMTgyNTU2NjItNzg2NjA0ZjEtYmI5MC00ZWEyLTg1ZTctZWIwNjZiMmY4MzU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDA1MTc1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjYjc4YjE5NDE1MmYwOTIzMWY2MmM4MTQ0NTc2NWU0MzM0OTM1OTA1Mjk1NGY2ZGQwMzUzNTM2MWNhZmE0MTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LrpEarOmG_BbC6ThB4jibOr7nonP-qT6SoGqROT-5mg)

哈哈，我也是这个报错，这里还有我，哈哈

**Comment by T8star1984** [comment]
hi ,you can see the linjian-ufo have same problem.And I scan the closed issue ,I find other have same problem too.

**Comment by peteromallet** [comment]
Hi @T8mars @T8star1984, @linjian-ufo, a potential fix has been implemented into one of the nodes this uses - can you test and let me know if it re-occurs?

**Comment by T8star1984** [comment]
okay ,I will test it and report to you as soon as possible

**Comment by T8star1984** [comment]
![QQ图片20240405182152](https://github.com/banodoco/Steerable-Motion/assets/161950228/7fb21b39-0fe7-488e-9bec-0e6e81f843f4)
I tried it just now,it show new error,It seemly say the cuda and pytorch is im compatible.but I checkt it and the version is suit and it run well in other workflow

**Comment by T8star1984** [comment]
my torch is 2.2.1  cuda is 12.1 xformers is 0.0.25

**Comment by T8star1984** [comment]
When I use Torch 2.12 ,cuda 12.1 and xformers 0.0.25,the workflow works normally,but I need try again

**Comment by T8star1984** [comment]
mybe the node don't support new torch ,cuda ,xfomers version

**Comment by T8star1984** [comment]
![微信图片_20240405221316](https://github.com/banodoco/Steerable-Motion/assets/161950228/007fb815-f368-4348-8fb4-2fe94bc96ce9)
![QQ图片20240405221932](https://github.com/banodoco/Steerable-Motion/assets/161950228/9107320f-a736-4c98-b7ef-e055ff35b74f)


it has new problem ,4 picture cost 3 hours!the gpu usage rate  is always 99%,I ask other users,they use new one the gpu useage overflow.

**Comment by T8star1984** [comment]
Prompt executed in 12519.21 seconds。last version only cost a few minutes

**Comment by T8star1984** [comment]
yes,I use the Shared graphics memory mode because of another one run the new version and graphics memory overflow.but last version have no this problem.let me try high VRAM mode and tell you result again

**Comment by T8star1984** [comment]
it's quicker than last time and don't report error any more

**Comment by T8star1984** [comment]
Today I generate a new one,it spend an afternoon time and untile now it had been finish.And no any tips,Can you optimize it?The console is stationary.and gpu usage is not high.I feel some problem happening.
![QQ图片20240406182916](https://github.com/banodoco/Steerable-Motion/assets/161950228/35f8cb74-da61-4dc3-8b55-8fa1acb8893d)

**Comment by T8star1984** [comment]
Finally, the problem was solved. I downloaded the latest "musetalk" node, which automatically mounts the model when starting COMFYUI, requiring 8GB of graphics memory directly, resulting in gpu overflow and running lag issues. Thank you for your reply in the past few days. I have resolved all the issues. Thank you for your node, it is very useful

**Comment by peteromallet** [comment]
> Finally, the problem was solved. I downloaded the latest "musetalk" node, which automatically mounts the model when starting COMFYUI, requiring 8GB of graphics memory directly, resulting in gpu overflow and running lag issues. Thank you for your reply in the past few days. I have resolved all the issues. Thank you for your node, it is very useful

That's great to hear and thank you so much for your compliment!
