### ISSUE TITLE
Error when running default workflow

### ISSUE THREAD

**Issue by MrSassyGit** [banodoco/Steerable-Motion#50]
I get this error when running, no changes to the nodes or settings and only using 2 square images.

"Error occurred when executing KSampler Adv. (Efficient):
mat1 and mat2 shapes cannot be multiplied (1232x2048 and 768x320)"

**Comment by vikiiing** [comment]
Error occurred when executing KSampler Adv. (Efficient):

ModelPatcherAndInjector.unpatch_model() got an unexpected keyword argument 'unpatch_weights'

**Comment by peteromallet** [comment]
Have you updated your Comfy and nodes to the latest version?

**Comment by MrSassyGit** [comment]
Now working after updating and redownloading the workflow (it was changed).
