### ISSUE TITLE
SBSR-15.safetensors

### ISSUE THREAD

**Issue by amnesicloud** [banodoco/Steerable-Motion#51]
Hi, 
I've checked your demo, great work!

however when I'm trying to reproduce your demo workflow(https://github.com/banodoco/Steerable-Motion/blob/main/demo/SuperBeasts-POM-SmoothBatchCreative-V1.3.json) I got a problem with SBSR-15.safetensors lora, I'm not sure if this is replaceable, so I tried to search for this lora, but could not find it (civitai, huggingface, google..), so I'm wondering can you help me out where can i find this lora?

Thx

**Comment by peteromallet** [comment]
I think that's the AD v.3 adapter that you can find [here](https://huggingface.co/guoyww/animatediff/blob/main/v3_sd15_adapter.ckpt) but it probably works fine without it tbh
