### ISSUE TITLE
Process Error

### ISSUE THREAD

**Issue by Ema81xsd** [banodoco/Steerable-Motion#54]
I'm new to this, I did follow all the steps but I get this stall: 

[AnimateDiffEvo] - INFO - Loading motion LoRA WAS26.safetensors
[AnimateDiffEvo] - INFO - Applying a v1 LoRA (WAS26.safetensors) to a v3 motion model.
Requested to load AutoencoderKL
Loading 1 new model
loading in lowvram mode 64.0
[AnimateDiffEvo] - INFO - Sliding context window activated - latents passed in (23) greater than context_length 16.
[AnimateDiffEvo] - INFO - Using motion module v3_sd15_mm.ckpt:v3.
Requested to load AnimateDiffModel
Requested to load BaseModel
Requested to load SparseControlNet
Loading 3 new models
loading in lowvram mode 64.0
loading in lowvram mode 64.0
loading in lowvram mode 64.0
  0%|                                                                                           | 0/20 [00:00<?, ?it/s]

It does not progress at all and I can not figure it out why
Thanks

**Comment by peteromallet** [comment]
This is because your GPU doesn't have enough VRAM - try turn off high detail mode or use less frames
