### ISSUE TITLE
It crashes on mac

### ISSUE THREAD

**Issue by andulegal** [banodoco/Steerable-Motion#55]
Requested to load CLIPVisionModelProjection
Loading 1 new model
2024-04-15 00:54:27.916 python3[37032:1421792] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff20590bdb __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff202c9d92 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff205b92e6 -[NSException raise] + 9
	3   AppKit                              0x00007fff22d497f2 -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 321
	4   AppKit                              0x00007fff22d343e2 -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 1296
	5   AppKit                              0x00007fff22d33ecb -[NSWindow initWithContentRect:styleMask:backing:defer:] + 42
	6   _macosx.cpython-312-darwin.so       0x000000017bca95ae -[Window initWithContentRect:styleMask:backing:defer:withManager:] + 62
	7   _macosx.cpython-312-darwin.so       0x000000017bcaca01 FigureManager_init + 257
	8   python3                             0x000000010bd54b1c wrap_init + 12
	9   python3                             0x000000010bcc46e0 wrapperdescr_call + 640
	10  python3                             0x000000010be2481f _PyEval_EvalFrameDefault + 221791
	11  python3                             0x000000010bd5443d slot_tp_init + 317
	12  python3                             0x000000010bd47a27 type_call + 135
	13  python3                             0x000000010be2481f _PyEval_EvalFrameDefault + 221791
	14  python3                             0x000000010bcb9753 method_vectorcall + 371
	15  python3                             0x000000010be29763 _PyEval_EvalFrameDefault + 242083
	16  python3                             0x000000010bcb9753 method_vectorcall + 371
	17  python3                             0x000000010be29763 _PyEval_EvalFrameDefault + 242083
	18  python3                             0x000000010bcb96b9 method_vectorcall + 217
	19  python3                             0x000000010be29292 _PyEval_EvalFrameDefault + 240850
	20  python3                             0x000000010bcb97b4 method_vectorcall + 468
	21  python3                             0x000000010bf4a2e9 thread_run + 121
	22  python3                             0x000000010bec3e14 pythread_wrapper + 36
	23  libsystem_pthread.dylib             0x00007fff2041e8fc _pthread_start + 224
	24  libsystem_pthread.dylib             0x00007fff2041a443 thread_start + 15
)
libc++abi: terminating with uncaught exception of type NSException
Abort trap: 6

**Comment by peteromallet** [comment]
Mac currently isn't supported/tested - will try to get to it soon!
