### ISSUE TITLE
I think I found the problem, but I don't know how to fix it.

### ISSUE THREAD

**Issue by jokero3answer** [banodoco/Steerable-Motion#61]
When I ignore ComfyUl-Advanced-Controlnet and load animatediff, it reports an error.
![image](https://github.com/banodoco/Steerable-Motion/assets/130854108/ddbeb4af-ed9d-43ee-a7b8-030ff449a399)

When I ignored animate evoloed, it worked.![image](https://github.com/banodoco/Steerable-Motion/assets/130854108/2268d142-7b7b-4467-83f8-4cdbf92d1b60)

All node plugins including comfyui ontology are in the latest version, how can I fix this please, thank you very much!
@IDGallagher @peteromallet 
@AnyiRao

**Comment by peteromallet** [comment]
Answered no Discord but you need to update your Comfy/Advanced ControlNet nodes!
