### ISSUE TITLE
I think there should be "control_net_name" but there isn't in my version

### ISSUE THREAD

**Issue by splinter21** [banodoco/Steerable-Motion#66]
![1111111](https://github.com/banodoco/Steerable-Motion/assets/26759495/41976c09-b433-4bbb-827c-8657fc85810f)

**Comment by splinter21** [comment]
ComfyUI: 2166[c33412](2024-05-07)

**Comment by peteromallet** [comment]
You're using a very old version of the workflow @splinter21  - grab the new one here: https://github.com/banodoco/Steerable-Motion/blob/main/demo/creative_interpolation_example.json
