### ISSUE TITLE
So how can I use controlnet_tile to control it?

### ISSUE THREAD

**Issue by splinter21** [banodoco/Steerable-Motion#69]
https://github.com/banodoco/Steerable-Motion/issues/66
 I want to use tile to control the generated images more similar to the source images.
Just gerenate the interploated frames. Not style transformed by the checkpoint/lora.

**Comment by peteromallet** [comment]
That probably won't help - would dial up end_steps on the current controlnet to improve adherence: https://github.com/banodoco/Steerable-Motion/blob/main/demo/creative_interpolation_example.json
