### ISSUE TITLE
Integer node?

### ISSUE THREAD

**Issue by lunatico67** [banodoco/Steerable-Motion#70]
I get this error when load the creative_interpolation_example.json example :
When loading the graph, the following node types were not found:
Integer
Nodes that have failed to load will show as red on the graph.

**Comment by KewkLW** [comment]
Just add any integer node for width and height. The names of those nodes were changed so that version doesn't technically exist anymore. (It's not an SM node)

**Comment by peteromallet** [comment]
> I get this error when load the creative_interpolation_example.json example : When loading the graph, the following node types were not found: Integer Nodes that have failed to load will show as red on the graph.

This will be fixed in the latest version if you pull that too!

**Comment by lunatico67** [comment]
Thanks for the answers to both (KewkLW and peteromallet) of you.
Peteromallet, I update every day ComfyUI and its custom nodes, today I updated Steerable motion and it is not fixed yet the absence of the integer node.
