### ISSUE TITLE
Integer node?

### ISSUE THREAD

**Issue by lunatico67** [banodoco/Steerable-Motion#71]
![steerable](https://github.com/banodoco/Steerable-Motion/assets/79542282/7890e087-ac86-43fa-9dc0-d34442207429)

When i load the creative_interpolation_example.json i get this error, i press Install Missing custom nodes and nothing appears

**Comment by peteromallet** [comment]
Grab the latest workflow from here: https://github.com/banodoco/Steerable-Motion/blob/main/demo/creative_interpolation_example.json

**Comment by lunatico67** [comment]
A lot of thanks Peteromallet, now it loads perfect
