### ISSUE TITLE
Document dependencies for JSON example

### ISSUE THREAD

**Issue by niqodea** [banodoco/Steerable-Motion#8]
Hi, thank you for your work!

In loading the example I noticed a bunch of missing custom nodes. It would be great if these dependencies were documented in the README or the example was reworked to work out of the box without them.

**Comment by peteromallet** [comment]
Hi @niqodea, apologies, I mentioned in the documentation but maybe should have made it more prominent - I would recommend using [Comfy Manager](https://github.com/ltdrdata/ComfyUI-Manager) to install the dependencies - you can get them all in one click - "Install Missing Custom Nodes"

**Comment by peteromallet** [comment]
Will try to make it more prominent/obvious

**Comment by peteromallet** [comment]
Updated the Installation section of the README to try to make this more obvious

**Comment by niqodea** [comment]
Sorry, maybe it was obvious, not really a Comfy expert. Thank you!
