### ISSUE TITLE
Prompt outputs failed validation VHS_LoadImagesPath: - Custom validation failed for node: directory - Directory 'input/test_tom_fire/' cannot be found.

### ISSUE THREAD

**Issue by DarqueLilly** [banodoco/Steerable-Motion#81]
Im getting this error: Prompt outputs failed validation
VHS_LoadImagesPath:
- Custom validation failed for node: directory - Directory 'input/test_tom_fire/' cannot be found. 
Can anyone tell me what im missing. 
![EqlboF5xgw](https://github.com/banodoco/Steerable-Motion/assets/111714884/9f3d00b8-c585-4de2-b875-66e031f737ac)

**Comment by KewkLW** [comment]
You haven't loaded any images into it. Click the choose folder to upload button. If you're not using it select it and bypass it with ctrl+b.
