### ISSUE TITLE
ACN_SparseCtrlLoaderAdvanced 467: Return type mismatch between linked nodes: sparse_method, STRING != SPARSE_METHOD

### ISSUE THREAD

**Issue by LorisTecnology** [banodoco/Steerable-Motion#85]
Getting this error on the latest ComfyUI version

ACN_SparseCtrlLoaderAdvanced 467:
Return type mismatch between linked nodes: sparse_method, STRING != SPARSE_METHOD

**Comment by eaksor** [comment]
Hi, did you resolved your problem, I got the same...

**Comment by peteromallet** [comment]
Hi there, you need to update all of your nodes and it'll work
