### ISSUE TITLE
ipadapter location in comfy

### ISSUE THREAD

**Issue by 2blackbar** [banodoco/Steerable-Motion#9]
somehow after instsalled this in comfy all i need is ipadaptrs, so intalled them with manger but they still wont showup even after restarting comfyu, this is not nice, id like to know where to put them manuyalluy and its irritating that they made it friendlier to get models from manager but actuallyu  also made it cryptic as hell

**Comment by peteromallet** [comment]
Hey @2blackbar, you can drop them manually in ComfyUI/models/ipadapter if you wish but they should be already there if installed via comfy manager
